/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountPanel: typeof import('./components/AccountPanel.vue')['default']
    ChapterSidebar: typeof import('./components/rewrite/ChapterSidebar.vue')['default']
    DocumentCanvas: typeof import('./components/rewrite/DocumentCanvas.vue')['default']
    DocxRenderer: typeof import('./components/editor/DocxRenderer.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    OnlyOfficeRewriteWorkspace: typeof import('./components/editor/OnlyOfficeRewriteWorkspace.vue')['default']
    PataFixEditor: typeof import('./components/editor/PataFixEditor.vue')['default']
    PdfRenderer: typeof import('./components/editor/PdfRenderer.vue')['default']
    ProviderConfigPanel: typeof import('./components/ProviderConfigPanel.vue')['default']
    ReportView: typeof import('./components/ReportView.vue')['default']
    ReportWorkflowSidebar: typeof import('./components/ReportWorkflowSidebar.vue')['default']
    RewriteBottomActionBar: typeof import('./components/editor/RewriteBottomActionBar.vue')['default']
    RewriteDocumentPane: typeof import('./components/editor/RewriteDocumentPane.vue')['default']
    RewriteEditor: typeof import('./components/RewriteEditor.vue')['default']
    RewriteMainLayout: typeof import('./components/rewrite/RewriteMainLayout.vue')['default']
    RewriteOutlineNav: typeof import('./components/editor/RewriteOutlineNav.vue')['default']
    RewriteStatsBar: typeof import('./components/rewrite/RewriteStatsBar.vue')['default']
    RewriteSuggestionPanel: typeof import('./components/editor/RewriteSuggestionPanel.vue')['default']
    RewriteTopBar: typeof import('./components/editor/RewriteTopBar.vue')['default']
    RewriteTopNav: typeof import('./components/rewrite/RewriteTopNav.vue')['default']
    RewriteWorkspaceStatsBar: typeof import('./components/editor/RewriteWorkspaceStatsBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UnlockModal: typeof import('./components/UnlockModal.vue')['default']
  }
}
