from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import httpx


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Run a full closed-loop demo against the local API service."
    )
    parser.add_argument(
        "--base-url",
        default="http://127.0.0.1:8010",
        help="API base url, default: http://127.0.0.1:8010",
    )
    parser.add_argument(
        "--paper",
        default="data/demo_paper.txt",
        help="Path to the demo paper text file.",
    )
    parser.add_argument(
        "--output-dir",
        default=".dev/demo-output",
        help="Directory for exported markdown reports.",
    )
    parser.add_argument(
        "--feedback-dup",
        type=float,
        default=None,
        help="Override CNKI duplication percent feedback.",
    )
    parser.add_argument(
        "--feedback-aigc",
        type=float,
        default=None,
        help="Override CNKI AIGC percent feedback.",
    )
    parser.add_argument(
        "--provider",
        default="wanfang",
        choices=["wanfang", "vip", "turnitin"],
        help="Primary provider to fetch.",
    )
    args = parser.parse_args()

    base_url = args.base_url.rstrip("/")
    paper_path = Path(args.paper)
    if not paper_path.exists():
        raise SystemExit(f"paper file not found: {paper_path}")

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    with httpx.Client(base_url=base_url, timeout=60.0) as client:
        _check_health(client)
        provider_catalog = client.get("/v1/providers/config").json()["providers"]
        configured_providers = [
            item["provider"] for item in provider_catalog if item["configured"]
        ]
        if args.provider not in configured_providers:
            raise SystemExit(
                f"provider {args.provider} is not configured. configured providers: {', '.join(configured_providers) or 'none'}"
            )

        upload_payload = _upload_document(client, paper_path)
        analyze_payload = client.post(
            f"/v1/documents/{upload_payload['document_id']}/analyze"
        )
        analyze_payload.raise_for_status()
        run_payload = analyze_payload.json()
        report = client.get(f"/v1/runs/{run_payload['run_id']}/report")
        report.raise_for_status()
        report_payload = report.json()

        fetched_providers: list[str] = []
        for provider in configured_providers:
            fetch_response = client.post(
                "/v1/provider-results/fetch",
                json={
                    "document_id": upload_payload["document_id"],
                    "run_id": run_payload["run_id"],
                    "provider": provider,
                    "extra_payload": {"demo_trace": "closed-loop-demo"},
                },
            )
            fetch_response.raise_for_status()
            fetched_providers.append(provider)

        feedback_dup = args.feedback_dup
        if feedback_dup is None:
            feedback_dup = _clamp(
                report_payload["summary"]["predicted_cnki_dup"]["center_percent"] + 2.2,
                0.0,
                100.0,
            )
        feedback_aigc = args.feedback_aigc
        if feedback_aigc is None:
            feedback_aigc = _clamp(
                report_payload["summary"]["predicted_cnki_aigc"]["center_percent"]
                + 1.4,
                0.0,
                100.0,
            )

        feedback_response = client.post(
            "/v1/cnki-feedback",
            data={
                "document_id": upload_payload["document_id"],
                "predicted_run_id": run_payload["run_id"],
                "cnki_dup_percent": f"{feedback_dup:.1f}",
                "cnki_aigc_percent": f"{feedback_aigc:.1f}",
                "report_date": "2026-04-28",
                "notes": "generated by scripts/closed_loop_demo.py",
            },
        )
        feedback_response.raise_for_status()
        feedback_payload = feedback_response.json()

        train_response = client.post(
            "/v1/models/train-proxy",
            json={"model_type": "both", "activate": True, "min_samples": 1},
        )
        train_response.raise_for_status()
        train_payload = train_response.json()

        markdown_response = client.get(
            f"/v1/runs/{run_payload['run_id']}/report/markdown"
        )
        markdown_response.raise_for_status()
        markdown_path = output_dir / f"{run_payload['run_id']}.md"
        markdown_path.write_text(markdown_response.text, encoding="utf-8")

        model_status = client.get("/v1/models/status")
        model_status.raise_for_status()
        model_status_payload = model_status.json()

    print("")
    print("=== Closed Loop Demo Completed ===")
    print(f"Document ID: {upload_payload['document_id']}")
    print(f"Run ID:      {run_payload['run_id']}")
    print(f"Title:       {report_payload['title']}")
    print(f"Providers:   {', '.join(fetched_providers)}")
    print(
        "Prediction:  dup "
        f"{report_payload['summary']['predicted_cnki_dup']['low_percent']:.1f}% - "
        f"{report_payload['summary']['predicted_cnki_dup']['high_percent']:.1f}% | aigc "
        f"{report_payload['summary']['predicted_cnki_aigc']['low_percent']:.1f}% - "
        f"{report_payload['summary']['predicted_cnki_aigc']['high_percent']:.1f}%"
    )
    print(f"Feedback:    dup {feedback_dup:.1f}% / aigc {feedback_aigc:.1f}%")
    print(f"Calibration: {feedback_payload['calibration_version']}")
    print(
        f"Models:      {', '.join(item['version'] for item in train_payload['trained_models'])}"
    )
    print(f"Active:      {len(model_status_payload['active_models'])} active models")
    print(f"Markdown:    {markdown_path.resolve()}")
    print("")
    print(
        "Tip: Open the frontend at http://localhost:5174 to inspect the same run visually."
    )
    return 0


def _check_health(client: httpx.Client) -> None:
    response = client.get("/health")
    response.raise_for_status()


def _upload_document(client: httpx.Client, paper_path: Path) -> dict[str, Any]:
    content = paper_path.read_text(encoding="utf-8")
    response = client.post(
        "/v1/documents/upload",
        data={"title": "闭环演示论文", "subject": "教育学", "degree_level": "本科"},
        files={"file": (paper_path.name, content.encode("utf-8"), "text/plain")},
    )
    response.raise_for_status()
    return response.json()


def _clamp(value: float, low: float, high: float) -> float:
    return max(low, min(high, value))


if __name__ == "__main__":
    raise SystemExit(main())
